# Generated by Django 3.0.6 on 2020-05-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keeping_days', models.PositiveIntegerField()),
                ('kcalories', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/ingredients/')),
                ('fridger', models.CharField(choices=[('F', 'Freezer'), ('R', 'Refrigerator'), ('T', 'Room Temperature')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField()),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.IngredientInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
