# Generated by Django 3.0.6 on 2020-05-20 06:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keeping_days', models.PositiveIntegerField()),
                ('kcalories', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/ingredients/')),
                ('fridger', models.CharField(choices=[('F', 'Freezer'), ('R', 'Refrigerator'), ('T', 'Room Temperature')], max_length=2)),
                ('type', models.CharField(choices=[('vegetables', '채소/과일'), ('meat', '육류'), ('marine', '수산물'), ('grain', '곡물/견과류'), ('sauce', '양념/소스'), ('milk', '가공/유제품'), ('others', '기타')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyStoredIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(default=datetime.date.today)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyMemoIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
