# Generated by Django 3.0.6 on 2020-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedfood',
            name='type',
            field=models.CharField(choices=[('broth', '육수'), ('vegetables', '채소'), ('marine', '해산물'), ('meat', '고기/계란'), ('rice', '밥/쌀'), ('kimchi', '김치/발효'), ('dessert', '간식/디저트')], max_length=30),
        ),
    ]
