# Generated by Django 3.0.6 on 2020-05-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recommendedfood_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendedfood',
            old_name='detail',
            new_name='ingredients_detail',
        ),
        migrations.RenameField(
            model_name='recommendedfood',
            old_name='food',
            new_name='name',
        ),
    ]
