# Generated by Django 3.0.6 on 2020-06-28 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200628_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(regex='\\d\\d\\d\\d')]),
        ),
    ]
